### PR TITLE
adds support for lookup API with testing

### PR DESCRIPTION
**Pull request by sunil3590**
Adds support to perform address lookup. This API has the advantage that we can lookup multiple OSM IDs in one call and also, importance value can be obtained.

http://wiki.openstreetmap.org/wiki/Nominatim#Address_lookup

### CODE REVIEW

**Comment by sunil3590** [comment]
Lookup API can handle up to 50 OSM items. Added a case to handle and throw an exception for requests over 50 items.

**Comment by jeremiehuchet** [comment]
Hi @sunil3590,

First of all: thanks for your work ! 

I merged your PR. I reviewed the `Exception` thrown when user give more than 50 _osm_type_. In order to keep the library as simple as possible, we shouldn't implement validation of the request parameters in the client. It's a server-side issue.

I assume we have a communication failure if we send to the server a query it can't understand neither handle. So the `NominatimResponseHandler` will throw an `IOException` on any HTTP response code >= 400. 
This way we avoid implementing parameter validation in the NominatimClient implementation.

**Comment by sunil3590** [comment]
Hi @jeremiehuchet 

That's a good way to deal with the error. Great.

Do you have plans of making a new maven release for this update?

**Comment by jeremiehuchet** [comment]
I just released a new version 3.2

**Comment by sunil3590** [comment]
Thank you @jeremiehuchet 

A maven release for the sake of completeness!
http://mvnrepository.com/artifact/fr.dudie/nominatim-api

Would love to use a maven release in my project.

**Comment by jeremiehuchet** [comment]
[mvnrepository](http://mvnrepository.com/) isn't up-to-date, use [search.maven.org](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22fr.dudie%22%20AND%20a%3A%22nominatim-api%22)

**Pull request merged**
